<a href="https://colab.research.google.com/github/SS012022/Azhar_notebooks/blob/main/first.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# numpy

In [4]:
L=[12,"one",656.34]
L

[12, 'one', 656.34]

In [5]:
import numpy as np
a=np.array
print(type(a))

<class 'builtin_function_or_method'>


In [8]:
print(a)

<built-in function array>


In [9]:
a=np.array([10,20,40])
a

array([10, 20, 40])

In [10]:
import sys
x=range(100)
print("size of each element",sys.getsizeof(x))

size of each element 48


In [11]:
y=np.arange(100)
print("size of each element in numpy",y.itemsize)

size of each element in numpy 8


In [12]:
a=np.array(10)
print(a,type(a))

10 <class 'numpy.ndarray'>


In [14]:
ar=np.array((1,2,3))
print(ar,type(ar))

[1 2 3] <class 'numpy.ndarray'>


In [15]:
ar=np.array([[10,20,30],[1,2,3]])
print(ar,type(ar),ar.ndim)

[[10 20 30]
 [ 1  2  3]] <class 'numpy.ndarray'> 2


In [17]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(ar.ndim)

2


In [18]:
print(ar)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
print(ar.itemsize)

8


In [20]:
print(ar.dtype)

int64


In [21]:
print(ar.size)

12


In [22]:
print(ar.shape)

(4, 3)


In [23]:
ar1=ar.reshape(3,4)
print(ar1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
ar2=ar.reshape(6,2)
print(ar2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [25]:
ar3=ar.reshape(4,4)
print(ar3)


ValueError: cannot reshape array of size 12 into shape (4,4)

In [29]:
x=np.random.randint(2,6,size=3)
print(x)

[5 2 3]


In [30]:
y=np.random.random(size=10)
print(y)


[0.1277079  0.0267039  0.53383863 0.57464212 0.80631727 0.04440023
 0.50845766 0.00905697 0.6766824  0.75449939]


In [31]:
z=np.random.rand(3,4)
print(z)

[[0.8674728  0.16755321 0.14268486 0.47148648]
 [0.83608335 0.0909713  0.56343464 0.31442578]
 [0.06819397 0.08775529 0.7917275  0.50924107]]


In [36]:
q=np.arange(6).reshape(2,3)
print(q)

[[0 1 2]
 [3 4 5]]


In [39]:
w=np.arange(1,12,2)
print(w)

[ 1  3  5  7  9 11]


In [40]:
print(w.reshape(3,2))

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [41]:
e=np.arange(1,2,0.1)
print(e)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [44]:
r=np.zeros([2,2],dtype=int)
print(r)


[[0 0]
 [0 0]]


In [46]:
t=np.zeros((2,2),dtype=float)
print(t)

[[0. 0.]
 [0. 0.]]


In [47]:
y=np.zeros((2,2),dtype=[('x','float'),('y','int')])
print(y)

[[(0., 0) (0., 0)]
 [(0., 0) (0., 0)]]


In [51]:
w=np.arange(1,18,2.3,dtype=float).reshape(4,2)
print(w)

[[ 1.   3.3]
 [ 5.6  7.9]
 [10.2 12.5]
 [14.8 17.1]]


In [53]:
u=np.linspace(5,12,10) # generate 10 numbers between 5 to 15
print(u)

[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


In [55]:
i=np.arange(5,15,2).reshape(3,2) # here 2 is step
print(i)

ValueError: cannot reshape array of size 5 into shape (3,2)

In [56]:
u=np.linspace(5,12,15).reshape(5,3)
print(u)

[[ 5.   5.5  6. ]
 [ 6.5  7.   7.5]
 [ 8.   8.5  9. ]
 [ 9.5 10.  10.5]
 [11.  11.5 12. ]]


In [58]:
o=np.array([21,15,26,17,8])
print(o)

[21 15 26 17  8]


In [60]:
print("maximum:",o.max())
print("minimum:",o.min())
print("sum:",o.sum())
print("mean:",o.mean())

maximum: 26
minimum: 8
sum: 87
mean: 17.4


In [ ]:
axis=0 # represents column
axis=1 # represents rows

In [61]:
p=np.linspace(2,10,12).reshape(4,3)
print(p)

[[ 2.          2.72727273  3.45454545]
 [ 4.18181818  4.90909091  5.63636364]
 [ 6.36363636  7.09090909  7.81818182]
 [ 8.54545455  9.27272727 10.        ]]


In [64]:
print("maximum in array :",p.max())
print("maximum in columns :",p.max(axis=0))
print("maximum in rows:",p.max(axis=1))

maximum in array : 10.0
maximum in columns : [ 8.54545455  9.27272727 10.        ]
maximum in rows: [ 3.45454545  5.63636364  7.81818182 10.        ]


In [66]:
a=np.array([[11,43,23],[78,23,76],[21,34,67]])
a

array([[11, 43, 23],
       [78, 23, 76],
       [21, 34, 67]])

In [67]:
print("maximum in rows:",a.max(axis=1))
print("maximum in cols:",a.max(axis=0))

maximum in rows: [43 78 67]
maximum in cols: [78 43 76]


In [68]:
print("minimum in rows:",a.min(axis=1))
print("minimum in cols:",a.min(axis=0))

minimum in rows: [11 23 21]
minimum in cols: [11 23 23]


In [69]:
print("sum of rows:",a.sum(axis=1))
print("sum of cols:",a.sum(axis=0))

sum of rows: [ 77 177 122]
sum of cols: [110 100 166]


In [70]:
print(np.sqrt(a ))

[[3.31662479 6.55743852 4.79583152]
 [8.83176087 4.79583152 8.71779789]
 [4.58257569 5.83095189 8.18535277]]


In [74]:
print(np.mean(a))
print(np.std(a))

41.77777777777778
24.18804928875129


In [76]:
print(a.mean(axis=1))

[25.66666667 59.         40.66666667]


In [75]:
s=a.sum()
print(s/9)

41.77777777777778
