In [2]:
import numpy as np

In [7]:
a=np.arange(1,12,2)
a=a.reshape(3,2)
a

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [8]:
b=np.transpose(a)
b

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [10]:
d=np.ndarray.flatten(b)
d

array([ 1,  5,  9,  3,  7, 11])

In [14]:
e=b.reshape(1,6)
e

array([[ 1,  5,  9,  3,  7, 11]])

In [18]:
print (b.size)
w=b.reshape(1,b.size)
w

6


array([[ 1,  5,  9,  3,  7, 11]])

In [20]:
q=np.array([3,5,6,2,3,7,5,6,8,5,3,9])
q

array([3, 5, 6, 2, 3, 7, 5, 6, 8, 5, 3, 9])

In [22]:
t=np.unique(q)
t

array([2, 3, 5, 6, 7, 8, 9])

In [55]:
p=np.array([1,np.nan,2,4,6,np.nan],dtype=float).reshape(2,3)
p

array([[ 1., nan,  2.],
       [ 4.,  6., nan]])

In [56]:
np.count_nonzero(np.isnan(p))

2

In [58]:
r=p[np.isnan(p)==False]
r

array([1., 2., 4., 6.])

In [48]:
r.reshape(2,2)

array([[1., 2.],
       [4., 6.]])

In [ ]:
a=np.array([3,6,8])
b=np.array([5,8,4])
# SET operation